<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com</groupId>
    <artifactId>test-sakura-light-web</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>test-sakura-light-web-pgm-menu00</artifactId>
  <name>menu00</name>

  <dependencies>
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-dateut</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-chklog</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0050</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0060</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0070</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0080</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0090</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0100</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0110</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ms0120</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-oe0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-oe0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-oe0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-oe0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-oe0050</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-sh0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-sl0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-sl0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-sl0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-sl0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-pu0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-pu0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-pu0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-pu0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rc0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-iv0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-iv0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-iv0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-iv0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-iv0050</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ar0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ar0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ap0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-ap0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0050</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0060</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0070</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0080</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0090</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0100</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0110</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0120</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0130</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-rp0140</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0010</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0020</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0030</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0040</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0050</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0060</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0070</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0080</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- inter-program CALL dependency -->
    <dependency>
      <groupId>com</groupId>
      <artifactId>test-sakura-light-web-pgm-bt0090</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
