-- ============================================================
-- Schema auto-generated from COBOL FD definitions
-- Source: Cobol2Java generator (build-time, not runtime)
-- Tables: 1
-- ============================================================

-- COBOL FD: TRAN-FILE (INDEXED)
CREATE TABLE IF NOT EXISTS tran_file (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tr_id VARCHAR(16) DEFAULT '',
    tr_type_cd VARCHAR(2) DEFAULT '',
    tr_cat_cd SMALLINT DEFAULT 0,
    tr_source VARCHAR(10) DEFAULT '',
    tr_desc VARCHAR(100) DEFAULT '',
    tr_amt DECIMAL(11,2) DEFAULT 0,
    tr_merchant_id INTEGER DEFAULT 0,
    tr_merchant_name VARCHAR(50) DEFAULT '',
    tr_merchant_city VARCHAR(50) DEFAULT '',
    tr_merchant_zip VARCHAR(10) DEFAULT '',
    tr_card_num VARCHAR(16) DEFAULT '',
    tr_orig_ts VARCHAR(26) DEFAULT '',
    tr_proc_ts VARCHAR(26) DEFAULT '',
    UNIQUE (tr_id)
);

-- Total: 1 tables generated
