package com.sakura;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point for Spring Batch jobs (batch cohort). Generated by Cobol2Java.
 *
 * <p>Launch: java -jar <app>.jar --spring.batch.job.name=<Prog>Job Runs the named job, then exits
 * with its completion code.
 */
@SpringBootApplication
public class AppLauncher {

    public static void main(String[] args) {
        System.exit(SpringApplication.exit(SpringApplication.run(AppLauncher.class, args)));
    }
}
