package com.sakura;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point for the WebSocket screen server (web cohort). Generated by Cobol2Java.
 *
 * <p>Launch: java -jar <app>.jar --screen.renderer=websocket Serves every screen program over
 * /ws/{programId}; the context stays alive.
 */
@SpringBootApplication
public class WebApplication {

    /**
     * Classes resolved lazily from spawned WebSocket worker threads can throw {@code
     * NoClassDefFoundError} under the Spring Boot fat-JAR launcher (nested {@code BOOT-INF/lib}
     * archives are opened on demand and the path is fragile in non-main threads). Force-loading
     * them from {@code main} caches the class definitions in metaspace before any worker spawns.
     */
    private static final String[] EAGER_LOAD_CLASSES = {
        "org.springframework.transaction.support.TransactionSynchronizationManager",
        "org.springframework.transaction.support.TransactionTemplate",
        "org.springframework.transaction.support.DefaultTransactionStatus",
        "org.springframework.transaction.support.DefaultTransactionDefinition",
        "org.springframework.transaction.support.AbstractPlatformTransactionManager",
        "ch.qos.logback.classic.spi.ThrowableProxy",
        "ch.qos.logback.classic.spi.ThrowableProxyUtil",
        "ch.qos.logback.classic.spi.PackagingDataCalculator",
    };

    public static void main(String[] args) {
        preloadLazyClasses();
        SpringApplication.run(WebApplication.class, args);
    }

    private static void preloadLazyClasses() {
        for (String fqn : EAGER_LOAD_CLASSES) {
            try {
                Class.forName(fqn);
            } catch (ClassNotFoundException ignored) {
            }
        }
    }
}
