-- ============================================================
-- Schema auto-generated from COBOL FD definitions
-- Source: Cobol2Java generator (build-time, not runtime)
-- Tables: 33
-- ============================================================

-- COBOL FD: MSGF (INDEXED)
CREATE TABLE IF NOT EXISTS msgf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mg_code VARCHAR(6) DEFAULT '',
    mg_text VARCHAR(60) DEFAULT '',
    UNIQUE (mg_code)
);

-- COBOL FD: SYSCF (INDEXED)
CREATE TABLE IF NOT EXISTS syscf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sy_key SMALLINT DEFAULT 0,
    sy_company_name VARCHAR(40) DEFAULT '',
    sy_company_zip VARCHAR(8) DEFAULT '',
    sy_company_addr VARCHAR(40) DEFAULT '',
    sy_company_tel VARCHAR(15) DEFAULT '',
    sy_fiscal_start SMALLINT DEFAULT 0,
    sy_curr_ym INTEGER DEFAULT 0,
    sy_last_day_close INTEGER DEFAULT 0,
    sy_last_mon_close INTEGER DEFAULT 0,
    sy_tax_dflt_rate DECIMAL(5,3) DEFAULT 0,
    sy_dec_round SMALLINT DEFAULT 0,
    UNIQUE (sy_key)
);

-- COBOL FD: NUMCF (INDEXED)
CREATE TABLE IF NOT EXISTS numcf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_key VARCHAR(8) DEFAULT '',
    nm_prefix VARCHAR(2) DEFAULT '',
    nm_current BIGINT DEFAULT 0,
    nm_width SMALLINT DEFAULT 0,
    UNIQUE (nm_key)
);

-- COBOL FD: TAXF (INDEXED)
CREATE TABLE IF NOT EXISTS taxf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_code SMALLINT DEFAULT 0,
    tx_start_date INTEGER DEFAULT 0,
    tx_rate DECIMAL(5,3) DEFAULT 0,
    tx_name VARCHAR(20) DEFAULT '',
    UNIQUE (tx_code tx_start_date)
);

-- COBOL FD: REGNF (INDEXED)
CREATE TABLE IF NOT EXISTS regnf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rg_code SMALLINT DEFAULT 0,
    rg_name VARCHAR(30) DEFAULT '',
    rg_del_flag SMALLINT DEFAULT 0,
    UNIQUE (rg_code)
);

-- COBOL FD: DEPTF (INDEXED)
CREATE TABLE IF NOT EXISTS deptf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dp_code SMALLINT DEFAULT 0,
    dp_name VARCHAR(30) DEFAULT '',
    dp_parent SMALLINT DEFAULT 0,
    dp_del_flag SMALLINT DEFAULT 0,
    UNIQUE (dp_code)
);

-- COBOL FD: CATGF (INDEXED)
CREATE TABLE IF NOT EXISTS catgf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ct_code SMALLINT DEFAULT 0,
    ct_name VARCHAR(30) DEFAULT '',
    ct_parent SMALLINT DEFAULT 0,
    ct_level SMALLINT DEFAULT 0,
    ct_del_flag SMALLINT DEFAULT 0,
    UNIQUE (ct_code)
);

-- COBOL FD: BANKF (INDEXED)
CREATE TABLE IF NOT EXISTS bankf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bk_code SMALLINT DEFAULT 0,
    bk_name VARCHAR(30) DEFAULT '',
    bk_branch VARCHAR(30) DEFAULT '',
    bk_del_flag SMALLINT DEFAULT 0,
    UNIQUE (bk_code)
);

-- COBOL FD: WHSEF (INDEXED)
CREATE TABLE IF NOT EXISTS whsef (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code SMALLINT DEFAULT 0,
    wh_name VARCHAR(30) DEFAULT '',
    wh_zip VARCHAR(8) DEFAULT '',
    wh_addr VARCHAR(40) DEFAULT '',
    wh_tel VARCHAR(15) DEFAULT '',
    wh_type SMALLINT DEFAULT 0,
    wh_manager SMALLINT DEFAULT 0,
    wh_del_flag SMALLINT DEFAULT 0,
    UNIQUE (wh_code)
);

-- COBOL FD: STAFF (INDEXED)
CREATE TABLE IF NOT EXISTS staff (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sf_code SMALLINT DEFAULT 0,
    sf_name VARCHAR(30) DEFAULT '',
    sf_kana VARCHAR(30) DEFAULT '',
    sf_dept SMALLINT DEFAULT 0,
    sf_tel VARCHAR(15) DEFAULT '',
    sf_email VARCHAR(40) DEFAULT '',
    sf_title VARCHAR(20) DEFAULT '',
    sf_del_flag SMALLINT DEFAULT 0,
    UNIQUE (sf_code)
);

-- COBOL FD: USERF (INDEXED)
CREATE TABLE IF NOT EXISTS userf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    us_code INTEGER DEFAULT 0,
    us_login VARCHAR(12) DEFAULT '',
    us_password VARCHAR(16) DEFAULT '',
    us_name VARCHAR(30) DEFAULT '',
    us_role SMALLINT DEFAULT 0,
    us_auth_master SMALLINT DEFAULT 0,
    us_auth_order SMALLINT DEFAULT 0,
    us_auth_sales SMALLINT DEFAULT 0,
    us_auth_purch SMALLINT DEFAULT 0,
    us_auth_close SMALLINT DEFAULT 0,
    us_last_login INTEGER DEFAULT 0,
    us_del_flag SMALLINT DEFAULT 0,
    UNIQUE (us_code)
);

-- COBOL FD: CUSTF (INDEXED)
CREATE TABLE IF NOT EXISTS custf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cu_code INTEGER DEFAULT 0,
    cu_name VARCHAR(40) DEFAULT '',
    cu_kana VARCHAR(40) DEFAULT '',
    cu_zip VARCHAR(8) DEFAULT '',
    cu_addr1 VARCHAR(40) DEFAULT '',
    cu_addr2 VARCHAR(40) DEFAULT '',
    cu_tel VARCHAR(15) DEFAULT '',
    cu_fax VARCHAR(15) DEFAULT '',
    cu_region SMALLINT DEFAULT 0,
    cu_staff SMALLINT DEFAULT 0,
    cu_close_day SMALLINT DEFAULT 0,
    cu_pay_month SMALLINT DEFAULT 0,
    cu_pay_day SMALLINT DEFAULT 0,
    cu_pay_method SMALLINT DEFAULT 0,
    cu_tax_type SMALLINT DEFAULT 0,
    cu_tax_round SMALLINT DEFAULT 0,
    cu_credit_limit BIGINT DEFAULT 0,
    cu_balance BIGINT DEFAULT 0,
    cu_price_rank SMALLINT DEFAULT 0,
    cu_bank_code SMALLINT DEFAULT 0,
    cu_bank_acct VARCHAR(20) DEFAULT '',
    cu_start_date INTEGER DEFAULT 0,
    cu_add_date INTEGER DEFAULT 0,
    cu_add_user INTEGER DEFAULT 0,
    cu_upd_date INTEGER DEFAULT 0,
    cu_upd_user INTEGER DEFAULT 0,
    cu_del_flag SMALLINT DEFAULT 0,
    UNIQUE (cu_code)
);

-- COBOL FD: SUPPF (INDEXED)
CREATE TABLE IF NOT EXISTS suppf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sp_code INTEGER DEFAULT 0,
    sp_name VARCHAR(40) DEFAULT '',
    sp_kana VARCHAR(40) DEFAULT '',
    sp_zip VARCHAR(8) DEFAULT '',
    sp_addr1 VARCHAR(40) DEFAULT '',
    sp_addr2 VARCHAR(40) DEFAULT '',
    sp_tel VARCHAR(15) DEFAULT '',
    sp_fax VARCHAR(15) DEFAULT '',
    sp_close_day SMALLINT DEFAULT 0,
    sp_pay_month SMALLINT DEFAULT 0,
    sp_pay_day SMALLINT DEFAULT 0,
    sp_pay_method SMALLINT DEFAULT 0,
    sp_tax_type SMALLINT DEFAULT 0,
    sp_balance BIGINT DEFAULT 0,
    sp_bank_code SMALLINT DEFAULT 0,
    sp_bank_acct VARCHAR(20) DEFAULT '',
    sp_add_date INTEGER DEFAULT 0,
    sp_add_user INTEGER DEFAULT 0,
    sp_upd_date INTEGER DEFAULT 0,
    sp_upd_user INTEGER DEFAULT 0,
    sp_del_flag SMALLINT DEFAULT 0,
    UNIQUE (sp_code)
);

-- COBOL FD: PRODF (INDEXED)
CREATE TABLE IF NOT EXISTS prodf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_code INTEGER DEFAULT 0,
    pr_name VARCHAR(40) DEFAULT '',
    pr_kana VARCHAR(40) DEFAULT '',
    pr_spec VARCHAR(30) DEFAULT '',
    pr_category SMALLINT DEFAULT 0,
    pr_barcode VARCHAR(13) DEFAULT '',
    pr_unit VARCHAR(6) DEFAULT '',
    pr_std_cost DECIMAL(11,2) DEFAULT 0,
    pr_last_cost DECIMAL(11,2) DEFAULT 0,
    pr_list_price DECIMAL(11,2) DEFAULT 0,
    pr_price_tbl_0_pr_rank_price DECIMAL(11,2) DEFAULT 0,
    pr_price_tbl_1_pr_rank_price DECIMAL(11,2) DEFAULT 0,
    pr_price_tbl_2_pr_rank_price DECIMAL(11,2) DEFAULT 0,
    pr_price_tbl_3_pr_rank_price DECIMAL(11,2) DEFAULT 0,
    pr_price_tbl_4_pr_rank_price DECIMAL(11,2) DEFAULT 0,
    pr_tax_category SMALLINT DEFAULT 0,
    pr_safety_stock INTEGER DEFAULT 0,
    pr_reorder_point INTEGER DEFAULT 0,
    pr_reorder_qty INTEGER DEFAULT 0,
    pr_lead_days SMALLINT DEFAULT 0,
    pr_dflt_supp INTEGER DEFAULT 0,
    pr_dflt_whse SMALLINT DEFAULT 0,
    pr_stock_mng SMALLINT DEFAULT 0,
    pr_add_date INTEGER DEFAULT 0,
    pr_add_user INTEGER DEFAULT 0,
    pr_upd_date INTEGER DEFAULT 0,
    pr_upd_user INTEGER DEFAULT 0,
    pr_del_flag SMALLINT DEFAULT 0,
    UNIQUE (pr_code)
);

-- COBOL FD: CPRCF (INDEXED)
CREATE TABLE IF NOT EXISTS cprcf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cp_cust INTEGER DEFAULT 0,
    cp_prod INTEGER DEFAULT 0,
    cp_price DECIMAL(11,2) DEFAULT 0,
    cp_start_date INTEGER DEFAULT 0,
    cp_end_date INTEGER DEFAULT 0,
    cp_del_flag SMALLINT DEFAULT 0,
    UNIQUE (cp_cust cp_prod)
);

-- COBOL FD: STOKF (INDEXED)
CREATE TABLE IF NOT EXISTS stokf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sk_prod INTEGER DEFAULT 0,
    sk_whse SMALLINT DEFAULT 0,
    sk_onhand INTEGER DEFAULT 0,
    sk_allocated INTEGER DEFAULT 0,
    sk_on_order INTEGER DEFAULT 0,
    sk_avg_cost DECIMAL(11,2) DEFAULT 0,
    sk_last_in_date INTEGER DEFAULT 0,
    sk_last_out_date INTEGER DEFAULT 0,
    sk_ytd_in BIGINT DEFAULT 0,
    sk_ytd_out BIGINT DEFAULT 0,
    sk_location VARCHAR(10) DEFAULT '',
    UNIQUE (sk_prod sk_whse)
);

-- COBOL FD: ORDHF (INDEXED)
CREATE TABLE IF NOT EXISTS ordhf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oh_no BIGINT DEFAULT 0,
    oh_date INTEGER DEFAULT 0,
    oh_cust INTEGER DEFAULT 0,
    oh_staff SMALLINT DEFAULT 0,
    oh_whse SMALLINT DEFAULT 0,
    oh_due_date INTEGER DEFAULT 0,
    oh_cust_po VARCHAR(20) DEFAULT '',
    oh_tax_type SMALLINT DEFAULT 0,
    oh_amount BIGINT DEFAULT 0,
    oh_tax_amount BIGINT DEFAULT 0,
    oh_total BIGINT DEFAULT 0,
    oh_status SMALLINT DEFAULT 0,
    oh_lines SMALLINT DEFAULT 0,
    oh_remark VARCHAR(40) DEFAULT '',
    oh_add_date INTEGER DEFAULT 0,
    oh_add_user INTEGER DEFAULT 0,
    oh_upd_date INTEGER DEFAULT 0,
    oh_upd_user INTEGER DEFAULT 0,
    oh_del_flag SMALLINT DEFAULT 0,
    UNIQUE (oh_no)
);

-- COBOL FD: ORDDF (INDEXED)
CREATE TABLE IF NOT EXISTS orddf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    od_no BIGINT DEFAULT 0,
    od_line SMALLINT DEFAULT 0,
    od_prod INTEGER DEFAULT 0,
    od_whse SMALLINT DEFAULT 0,
    od_qty INTEGER DEFAULT 0,
    od_unit_price DECIMAL(11,2) DEFAULT 0,
    od_amount BIGINT DEFAULT 0,
    od_tax_category SMALLINT DEFAULT 0,
    od_shipped_qty INTEGER DEFAULT 0,
    od_alloc_qty INTEGER DEFAULT 0,
    od_due_date INTEGER DEFAULT 0,
    od_status SMALLINT DEFAULT 0,
    od_remark VARCHAR(30) DEFAULT '',
    UNIQUE (od_no od_line)
);

-- COBOL FD: SHPHF (INDEXED)
CREATE TABLE IF NOT EXISTS shphf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xh_no BIGINT DEFAULT 0,
    xh_date INTEGER DEFAULT 0,
    xh_order BIGINT DEFAULT 0,
    xh_cust INTEGER DEFAULT 0,
    xh_whse SMALLINT DEFAULT 0,
    xh_staff SMALLINT DEFAULT 0,
    xh_status SMALLINT DEFAULT 0,
    xh_lines SMALLINT DEFAULT 0,
    xh_remark VARCHAR(40) DEFAULT '',
    xh_add_date INTEGER DEFAULT 0,
    xh_add_user INTEGER DEFAULT 0,
    xh_del_flag SMALLINT DEFAULT 0,
    UNIQUE (xh_no)
);

-- COBOL FD: SHPDF (INDEXED)
CREATE TABLE IF NOT EXISTS shpdf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xd_no BIGINT DEFAULT 0,
    xd_line SMALLINT DEFAULT 0,
    xd_order BIGINT DEFAULT 0,
    xd_order_line SMALLINT DEFAULT 0,
    xd_prod INTEGER DEFAULT 0,
    xd_whse SMALLINT DEFAULT 0,
    xd_qty INTEGER DEFAULT 0,
    xd_unit_price DECIMAL(11,2) DEFAULT 0,
    xd_amount BIGINT DEFAULT 0,
    xd_unit_cost DECIMAL(11,2) DEFAULT 0,
    UNIQUE (xd_no xd_line)
);

-- COBOL FD: INVHF (INDEXED)
CREATE TABLE IF NOT EXISTS invhf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ih_no BIGINT DEFAULT 0,
    ih_date INTEGER DEFAULT 0,
    ih_cust INTEGER DEFAULT 0,
    ih_staff SMALLINT DEFAULT 0,
    ih_ship_no BIGINT DEFAULT 0,
    ih_close_ym INTEGER DEFAULT 0,
    ih_tax_type SMALLINT DEFAULT 0,
    ih_amount BIGINT DEFAULT 0,
    ih_tax_amount BIGINT DEFAULT 0,
    ih_total BIGINT DEFAULT 0,
    ih_cost_total BIGINT DEFAULT 0,
    ih_status SMALLINT DEFAULT 0,
    ih_kind SMALLINT DEFAULT 0,
    ih_lines SMALLINT DEFAULT 0,
    ih_remark VARCHAR(40) DEFAULT '',
    ih_add_date INTEGER DEFAULT 0,
    ih_add_user INTEGER DEFAULT 0,
    ih_upd_date INTEGER DEFAULT 0,
    ih_upd_user INTEGER DEFAULT 0,
    ih_del_flag SMALLINT DEFAULT 0,
    UNIQUE (ih_no)
);

-- COBOL FD: INVDF (INDEXED)
CREATE TABLE IF NOT EXISTS invdf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_no BIGINT DEFAULT 0,
    id_line SMALLINT DEFAULT 0,
    id_prod INTEGER DEFAULT 0,
    id_whse SMALLINT DEFAULT 0,
    id_qty INTEGER DEFAULT 0,
    id_unit_price DECIMAL(11,2) DEFAULT 0,
    id_amount BIGINT DEFAULT 0,
    id_unit_cost DECIMAL(11,2) DEFAULT 0,
    id_cost_amount BIGINT DEFAULT 0,
    id_tax_category SMALLINT DEFAULT 0,
    id_remark VARCHAR(30) DEFAULT '',
    UNIQUE (id_no id_line)
);

-- COBOL FD: POHF (INDEXED)
CREATE TABLE IF NOT EXISTS pohf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ph_no BIGINT DEFAULT 0,
    ph_date INTEGER DEFAULT 0,
    ph_supp INTEGER DEFAULT 0,
    ph_whse SMALLINT DEFAULT 0,
    ph_staff SMALLINT DEFAULT 0,
    ph_due_date INTEGER DEFAULT 0,
    ph_tax_type SMALLINT DEFAULT 0,
    ph_amount BIGINT DEFAULT 0,
    ph_tax_amount BIGINT DEFAULT 0,
    ph_total BIGINT DEFAULT 0,
    ph_status SMALLINT DEFAULT 0,
    ph_lines SMALLINT DEFAULT 0,
    ph_remark VARCHAR(40) DEFAULT '',
    ph_add_date INTEGER DEFAULT 0,
    ph_add_user INTEGER DEFAULT 0,
    ph_del_flag SMALLINT DEFAULT 0,
    UNIQUE (ph_no)
);

-- COBOL FD: PODF (INDEXED)
CREATE TABLE IF NOT EXISTS podf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pd_no BIGINT DEFAULT 0,
    pd_line SMALLINT DEFAULT 0,
    pd_prod INTEGER DEFAULT 0,
    pd_whse SMALLINT DEFAULT 0,
    pd_qty INTEGER DEFAULT 0,
    pd_unit_cost DECIMAL(11,2) DEFAULT 0,
    pd_amount BIGINT DEFAULT 0,
    pd_recv_qty INTEGER DEFAULT 0,
    pd_due_date INTEGER DEFAULT 0,
    pd_status SMALLINT DEFAULT 0,
    UNIQUE (pd_no pd_line)
);

-- COBOL FD: RCVHF (INDEXED)
CREATE TABLE IF NOT EXISTS rcvhf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rh_no BIGINT DEFAULT 0,
    rh_date INTEGER DEFAULT 0,
    rh_po BIGINT DEFAULT 0,
    rh_supp INTEGER DEFAULT 0,
    rh_whse SMALLINT DEFAULT 0,
    rh_status SMALLINT DEFAULT 0,
    rh_lines SMALLINT DEFAULT 0,
    rh_remark VARCHAR(40) DEFAULT '',
    rh_add_date INTEGER DEFAULT 0,
    rh_add_user INTEGER DEFAULT 0,
    rh_del_flag SMALLINT DEFAULT 0,
    UNIQUE (rh_no)
);

-- COBOL FD: RCVDF (INDEXED)
CREATE TABLE IF NOT EXISTS rcvdf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rd_no BIGINT DEFAULT 0,
    rd_line SMALLINT DEFAULT 0,
    rd_po BIGINT DEFAULT 0,
    rd_po_line SMALLINT DEFAULT 0,
    rd_prod INTEGER DEFAULT 0,
    rd_whse SMALLINT DEFAULT 0,
    rd_qty INTEGER DEFAULT 0,
    rd_unit_cost DECIMAL(11,2) DEFAULT 0,
    rd_amount BIGINT DEFAULT 0,
    UNIQUE (rd_no rd_line)
);

-- COBOL FD: PURHF (INDEXED)
CREATE TABLE IF NOT EXISTS purhf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vh_no BIGINT DEFAULT 0,
    vh_date INTEGER DEFAULT 0,
    vh_supp INTEGER DEFAULT 0,
    vh_recv_no BIGINT DEFAULT 0,
    vh_close_ym INTEGER DEFAULT 0,
    vh_tax_type SMALLINT DEFAULT 0,
    vh_amount BIGINT DEFAULT 0,
    vh_tax_amount BIGINT DEFAULT 0,
    vh_total BIGINT DEFAULT 0,
    vh_status SMALLINT DEFAULT 0,
    vh_kind SMALLINT DEFAULT 0,
    vh_lines SMALLINT DEFAULT 0,
    vh_remark VARCHAR(40) DEFAULT '',
    vh_add_date INTEGER DEFAULT 0,
    vh_add_user INTEGER DEFAULT 0,
    vh_del_flag SMALLINT DEFAULT 0,
    UNIQUE (vh_no)
);

-- COBOL FD: PURDF (INDEXED)
CREATE TABLE IF NOT EXISTS purdf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vd_no BIGINT DEFAULT 0,
    vd_line SMALLINT DEFAULT 0,
    vd_prod INTEGER DEFAULT 0,
    vd_whse SMALLINT DEFAULT 0,
    vd_qty INTEGER DEFAULT 0,
    vd_unit_cost DECIMAL(11,2) DEFAULT 0,
    vd_amount BIGINT DEFAULT 0,
    vd_tax_category SMALLINT DEFAULT 0,
    UNIQUE (vd_no vd_line)
);

-- COBOL FD: ARLF (INDEXED)
CREATE TABLE IF NOT EXISTS arlf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    al_seq BIGINT DEFAULT 0,
    al_cust INTEGER DEFAULT 0,
    al_date INTEGER DEFAULT 0,
    al_close_ym INTEGER DEFAULT 0,
    al_kind SMALLINT DEFAULT 0,
    al_ref_type SMALLINT DEFAULT 0,
    al_ref_no BIGINT DEFAULT 0,
    al_debit BIGINT DEFAULT 0,
    al_credit BIGINT DEFAULT 0,
    al_balance BIGINT DEFAULT 0,
    al_remark VARCHAR(30) DEFAULT '',
    al_user INTEGER DEFAULT 0,
    UNIQUE (al_seq)
);

-- COBOL FD: APLF (INDEXED)
CREATE TABLE IF NOT EXISTS aplf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pl_seq BIGINT DEFAULT 0,
    pl_supp INTEGER DEFAULT 0,
    pl_date INTEGER DEFAULT 0,
    pl_close_ym INTEGER DEFAULT 0,
    pl_kind SMALLINT DEFAULT 0,
    pl_ref_type SMALLINT DEFAULT 0,
    pl_ref_no BIGINT DEFAULT 0,
    pl_debit BIGINT DEFAULT 0,
    pl_credit BIGINT DEFAULT 0,
    pl_balance BIGINT DEFAULT 0,
    pl_remark VARCHAR(30) DEFAULT '',
    pl_user INTEGER DEFAULT 0,
    UNIQUE (pl_seq)
);

-- COBOL FD: RCPTF (INDEXED)
CREATE TABLE IF NOT EXISTS rcptf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    re_no BIGINT DEFAULT 0,
    re_date INTEGER DEFAULT 0,
    re_cust INTEGER DEFAULT 0,
    re_method SMALLINT DEFAULT 0,
    re_amount BIGINT DEFAULT 0,
    re_bank_code SMALLINT DEFAULT 0,
    re_close_ym INTEGER DEFAULT 0,
    re_status SMALLINT DEFAULT 0,
    re_remark VARCHAR(30) DEFAULT '',
    re_add_date INTEGER DEFAULT 0,
    re_add_user INTEGER DEFAULT 0,
    re_del_flag SMALLINT DEFAULT 0,
    UNIQUE (re_no)
);

-- COBOL FD: PAYF (INDEXED)
CREATE TABLE IF NOT EXISTS payf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    py_no BIGINT DEFAULT 0,
    py_date INTEGER DEFAULT 0,
    py_supp INTEGER DEFAULT 0,
    py_method SMALLINT DEFAULT 0,
    py_amount BIGINT DEFAULT 0,
    py_bank_code SMALLINT DEFAULT 0,
    py_close_ym INTEGER DEFAULT 0,
    py_status SMALLINT DEFAULT 0,
    py_remark VARCHAR(30) DEFAULT '',
    py_add_date INTEGER DEFAULT 0,
    py_add_user INTEGER DEFAULT 0,
    py_del_flag SMALLINT DEFAULT 0,
    UNIQUE (py_no)
);

-- COBOL FD: SMOVF (INDEXED)
CREATE TABLE IF NOT EXISTS smovf (
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sm_seq BIGINT DEFAULT 0,
    sm_date INTEGER DEFAULT 0,
    sm_prod INTEGER DEFAULT 0,
    sm_whse SMALLINT DEFAULT 0,
    sm_kind SMALLINT DEFAULT 0,
    sm_qty INTEGER DEFAULT 0,
    sm_unit_cost DECIMAL(11,2) DEFAULT 0,
    sm_bal_after INTEGER DEFAULT 0,
    sm_ref_type SMALLINT DEFAULT 0,
    sm_ref_no BIGINT DEFAULT 0,
    sm_user INTEGER DEFAULT 0,
    UNIQUE (sm_seq)
);

-- Total: 33 tables generated
