import type { ScreenOverrides } from '../types/screenOverride'
// AUTO-GENERATED by bms-screen-modernize. Maps screenName(UPPER) → modern SFC.
// AI per-screen SFCs (src/programs/<prog>/) take precedence over the deterministic
// archetypes (src/programs/_archetypes/). Screens not listed fall back to ScreenView.
// A screen name owned by several programs dispatches on the program (byProgram).
import { byProgram } from './_archetypes/programSwitch'
import RecordScreen from './_archetypes/RecordScreen.vue'
import AI_ODACCTU_MACCTUA from './odacctu/MACCTUA.vue'
import AI_OCACCTV_MACCTVA from './ocacctv/MACCTVA.vue'
import AI_ODACCTV_MACCTVA from './odacctv/MACCTVA.vue'
import AI_OCACTIN_MACTINA from './ocactin/MACTINA.vue'
import AI_OCADMEN_MADMENA from './ocadmen/MADMENA.vue'
import AI_OCANLIN_MANLINA from './ocanlin/MANLINA.vue'
import AI_OCAUTHQ_MAUTHQA from './ocauthq/MAUTHQA.vue'
import AI_OCBILLP_MBILLPA from './ocbillp/MBILLPA.vue'
import AI_OCCARDA_MCARDAA from './occarda/MCARDAA.vue'
import AI_OCCARDL_MCARDLA from './occardl/MCARDLA.vue'
import AI_OCCARDU_MCARDUA from './occardu/MCARDUA.vue'
import AI_OCCARDV_MCARDVA from './occardv/MCARDVA.vue'
import AI_ODCARDV_MCARDVA from './odcardv/MCARDVA.vue'
import AI_OCCRDIN_MCRDINA from './occrdin/MCRDINA.vue'
import AI_OCCUSIN_MCUSINA from './occusin/MCUSINA.vue'
import AI_OCCUSTA_MCUSTAA from './occusta/MCUSTAA.vue'
import AI_OCCUSTL_MCUSTLA from './occustl/MCUSTLA.vue'
import AI_OCCUSTU_MCUSTUA from './occustu/MCUSTUA.vue'
import AI_OCCUSTV_MCUSTVA from './occustv/MCUSTVA.vue'
import AI_ODCUSTV_MCUSTVA from './odcustv/MCUSTVA.vue'
import AI_OCDGRP_MDGRPA from './ocdgrp/MDGRPA.vue'
import AI_OCMENU_MMENUA from './ocmenu/MMENUA.vue'
import AI_OCOPS_MOPSA from './ocops/MOPSA.vue'
import AI_OCPAUIN_MPAUINA from './ocpauin/MPAUINA.vue'
import AI_OCPWDCH_MPWDCHA from './ocpwdch/MPWDCHA.vue'
import AI_OCREPT_MREPTA from './ocrept/MREPTA.vue'
import AI_OCRPTMN_MRPTMNA from './ocrptmn/MRPTMNA.vue'
import AI_OCSGNON_MSGNONA from './ocsgnon/MSGNONA.vue'
import AI_OCSTMIN_MSTMINA from './ocstmin/MSTMINA.vue'
import AI_OCSTMV_MSTMVA from './ocstmv/MSTMVA.vue'
import AI_OCTCAT_MTCATA from './octcat/MTCATA.vue'
import AI_OCTRANA_MTRANAA from './octrana/MTRANAA.vue'
import AI_ODTRANA_MTRANAA from './odtrana/MTRANAA.vue'
import AI_OCTRANL_MTRANLA from './octranl/MTRANLA.vue'
import AI_ODTRANL_MTRANLA from './odtranl/MTRANLA.vue'
import AI_OCTRANV_MTRANVA from './octranv/MTRANVA.vue'
import AI_OCTRNIN_MTRNINA from './octrnin/MTRNINA.vue'
import AI_OCTSRCH_MTSRCHA from './octsrch/MTSRCHA.vue'
import AI_OCTTYP_MTTYPA from './octtyp/MTTYPA.vue'
import AI_OCUSRA_MUSRAA from './ocusra/MUSRAA.vue'
import AI_OCUSRD_MUSRDA from './ocusrd/MUSRDA.vue'
import AI_OCUSRL_MUSRLA from './ocusrl/MUSRLA.vue'
import AI_OCUSRU_MUSRUA from './ocusru/MUSRUA.vue'
import AI_OCUTIL_MUTILA from './ocutil/MUTILA.vue'

export const screenOverrides: ScreenOverrides = {
  'MACCTAA': RecordScreen,
  'MACCTLA': RecordScreen,
  'MACCTUA': byProgram({ 'ocacctu': RecordScreen, 'odacctu': AI_ODACCTU_MACCTUA }),
  'MACCTVA': byProgram({ 'ocacctv': AI_OCACCTV_MACCTVA, 'odacctv': AI_ODACCTV_MACCTVA }),
  'MACTINA': AI_OCACTIN_MACTINA,
  'MADMENA': AI_OCADMEN_MADMENA,
  'MANLINA': AI_OCANLIN_MANLINA,
  'MAUTHQA': AI_OCAUTHQ_MAUTHQA,
  'MBILLPA': AI_OCBILLP_MBILLPA,
  'MCARDAA': AI_OCCARDA_MCARDAA,
  'MCARDLA': AI_OCCARDL_MCARDLA,
  'MCARDUA': AI_OCCARDU_MCARDUA,
  'MCARDVA': byProgram({ 'occardv': AI_OCCARDV_MCARDVA, 'odcardv': AI_ODCARDV_MCARDVA }),
  'MCRDINA': AI_OCCRDIN_MCRDINA,
  'MCUSINA': AI_OCCUSIN_MCUSINA,
  'MCUSTAA': AI_OCCUSTA_MCUSTAA,
  'MCUSTLA': AI_OCCUSTL_MCUSTLA,
  'MCUSTUA': AI_OCCUSTU_MCUSTUA,
  'MCUSTVA': byProgram({ 'occustv': AI_OCCUSTV_MCUSTVA, 'odcustv': AI_ODCUSTV_MCUSTVA }),
  'MDGRPA': AI_OCDGRP_MDGRPA,
  'MMENUA': AI_OCMENU_MMENUA,
  'MOPSA': AI_OCOPS_MOPSA,
  'MPAUINA': AI_OCPAUIN_MPAUINA,
  'MPWDCHA': AI_OCPWDCH_MPWDCHA,
  'MREPTA': AI_OCREPT_MREPTA,
  'MRPTMNA': AI_OCRPTMN_MRPTMNA,
  'MSGNONA': AI_OCSGNON_MSGNONA,
  'MSTMINA': AI_OCSTMIN_MSTMINA,
  'MSTMVA': AI_OCSTMV_MSTMVA,
  'MTCATA': AI_OCTCAT_MTCATA,
  'MTRANAA': byProgram({ 'octrana': AI_OCTRANA_MTRANAA, 'odtrana': AI_ODTRANA_MTRANAA }),
  'MTRANLA': byProgram({ 'octranl': AI_OCTRANL_MTRANLA, 'odtranl': AI_ODTRANL_MTRANLA }),
  'MTRANVA': AI_OCTRANV_MTRANVA,
  'MTRNINA': AI_OCTRNIN_MTRNINA,
  'MTSRCHA': AI_OCTSRCH_MTSRCHA,
  'MTTYPA': AI_OCTTYP_MTTYPA,
  'MUSRAA': AI_OCUSRA_MUSRAA,
  'MUSRDA': AI_OCUSRD_MUSRDA,
  'MUSRLA': AI_OCUSRL_MUSRLA,
  'MUSRUA': AI_OCUSRU_MUSRUA,
  'MUTILA': AI_OCUTIL_MUTILA,
}
